version: '2'
services:
    matrixtracker-app:
        image: matrixtracker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://matrixtracker-mysql:3306/matrixtracker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=matrixtracker-elasticsearch:9300
        ports:
            - 8080:8080
    matrixtracker-mysql:
        extends:
            file: mysql.yml
            service: matrixtracker-mysql
    matrixtracker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: matrixtracker-elasticsearch
